[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11.6"
embedded-graphics = "0.8.1"
spin = "0.9.8"
talc = "4.2.0"
log = "0.4.20"